### ISSUE TITLE
using deprecated api

### ISSUE THREAD

**Issue by tagantroy** [yasuyuky/autocomplete-clang#58]
After update atom to 0.200 some functions working incorrect.
appears alert about using deprecated api.
on atom 0.199 working fine

**Comment by yasuyuky** [comment]
Thanks for your quick report.
I just released solved version.

Unfortunately, inline preview feature is disabled in the new version because it depends on deprecated feature.

I'm considering that using autocomplete-plus. 
(Now, the package bundled to atom itself)
It will be big change for the package.
(Proof of concept is here https://github.com/benogle/autocomplete-clang)
I'm going to suggest unification proposal.
If you have any idea, comment to the issue.
