### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by welkineins** [yasuyuky/autocomplete-clang#63]
This is a very good package for Atom to support C/C++ autocomplete.

However, it seems a little performance issue.

In my test, a small project with tens of c++ files (.h/.cpp), autocomplete take a observable delay (~0.5s) before it pop out. I think it's slow down the coding speed.

Can you provide information about how to speed up or using some cache to avoid calling clang every time?

Thank you.

Jack

**Comment by yasuyuky** [comment]
Thanks for your feedback.
I guess that using pre-compiled header may solve a performance issue.
I hope it can help you.

**Comment by the-drunk-coder** [comment]
Hmm even with a precompiled header, it's still quite slow ... 

Plus, it seems to be very resource-consuming ... like, when checking with htop, 100% CPU usage on all processor cores, just for autocompletion, and like 8 clang-autocomplete processes  (on a 100 line source file!).

Probably the problem is with clang, not with the plugin ...

**Comment by the-drunk-coder** [comment]
Ok, for now i have disabled autocomplete-clang, as it seemed to be getting even slower, slow enough to diminish productivity, rather than enhance it ... and i'm talking about projects with one file and ~350
lines.

I figure it might be a configuration issue, but i've got no idea where to look :(

**Comment by ZhengRui** [comment]
I got the same issue here, also if i press "tab" or "enter" key too fast, the autocompletion popup will simply disappear. If i disable this, the default autocomplete-plus works well.

**Comment by assumptionsoup** [comment]
I have to agree. Autocomplete-plus is wicked fast when clang autocomplete is disabled.  Enabling clang, it takes ~0.5 seconds to auto complete, and if I tab/enter complete too soon, the entire dialog is dismissed (and often times I'll end up with a tab in my code).  It's too slow for me to use right now on my small < 300 line project and I am on pretty good machine.

**Comment by lczech** [comment]
Similar issue here. When I quickly type a word, many many clang instances are spawned at the same time, which leads to a totally non-responsive atom window until these instances have finished running. This takes a few seconds, effectively freezing atom for the time:

![acp_clang](https://user-images.githubusercontent.com/4741887/39366833-5dd65c1a-4a35-11e8-9f6c-c3a989c9879d.png)

Why are that many clang instances needed when typing a single word?

**Comment by cata0309** [comment]
Is there anybody to fix this ? We need to make it faster

**Comment by kangshugang** [comment]
Here is simple way to improve the performance by caching the clang output, instead of spawning the clang process again and again, which is not necessary (as least from my testing).

Please edit codeCompletionAt function in the clang-provider.coffee file as follows:

  codeCompletionAt: (editor, row, column, language, prefix) ->
    if (@cache_path == editor.getPath() and @cache_row == row and @cache_column == column)
      @handleCompletionResult(@cache_outputs, @cache_code, prefix)
    else
      args = buildCodeCompletionArgs editor, row, column, language
      callback = (code, outputs, errors, resolve) =>
        @cache_path = editor.getPath()
        @cache_row = row
        @cache_column = column
        @cache_code = code
        @cache_outputs = outputs
        resolve(@handleCompletionResult(outputs, code, prefix))
      makeBufferedClangProcess editor, args, callback, editor.getText()

Clang autocomplete runs much faster!!!
Enjoy!

**Comment by yasuyuky** [comment]
How can we invalidate the cache when conditions change?

**Comment by kangshugang** [comment]
The cache is being used with the condition that the code completion request
is for the same file at the same position (row and column). If the
condition cannot be satisfied, clang will be spawned to get the new
results. The new results will overwrite the cache.

There is only one copy of cache. The cache will be used if the condition
meet, otherwise the cache will be overwritten. The cache cannot grow over
time and there is no need to release the cache.

Thanks.

**Comment by BeefaloKing** [comment]
Can we see an update on this? The problem is tremendously worse on windows as Anti Malware Executable also spins up to check out what clang is doing. Typing too fast can lead to 100% cpu usage with multiple hundreds of instances of clang and cause the entire system to feel unresponsive until they finish.
![image](https://user-images.githubusercontent.com/9630438/71327606-f83c1380-24c7-11ea-86af-7f6ec5186966.png)

**Comment by mp1994** [comment]
> Here is simple way to improve the performance by caching the clang output, instead of spawning the clang process again and again, which is not necessary (as least from my testing).
> 
> Please edit codeCompletionAt function in the clang-provider.coffee file as follows:
> 
> codeCompletionAt: (editor, row, column, language, prefix) ->
> if (@cache_path == editor.getPath() and @cache_row == row and @cache_column == column)
> @handleCompletionResult(@cache_outputs, @cache_code, prefix)
> else
> args = buildCodeCompletionArgs editor, row, column, language
> callback = (code, outputs, errors, resolve) =>
> @cache_path = editor.getPath()
> @cache_row = row
> @cache_column = column
> @cache_code = code
> @cache_outputs = outputs
> resolve(@handleCompletionResult(outputs, code, prefix))
> makeBufferedClangProcess editor, args, callback, editor.getText()
> 
> Clang autocomplete runs much faster!!!
> Enjoy!

It's giving me errors, possibly because of indentation issues?
