### ISSUE TITLE
Suggests inappropriate completions when typedef'ing struct 

### ISSUE THREAD

**Issue by ssfrr** [yasuyuky/autocomplete-clang#66]
When trying to type something like this:

```
typedef struct {
    uint8_t x;
    uint8_t y;
} foo;
```

I get up to typing in the first member and as soon as I type the semicolon I get snippet popups up a completion to define a new typedef at that point. This is particularly problematic because the next character I'll type is "enter" which by default will accept the given completion.

**Comment by yasuyuky** [comment]
Nice feedback. Thanks!

**Comment by ssfrr** [comment]
Thanks for the quick fix! It looks like this is also an issue after commas, e.g. while defining an enum or defining or calling a function. Do you want a separate issue for that?

**Comment by yasuyuky** [comment]
OK, Let's use this issue to fix that.

**Comment by ssfrr** [comment]
Also after a `:`, such as when defining cases for a switch statement.

**Comment by yasuyuky** [comment]
I found that things are a little bit complicated.
Some completions after commas are useful while defining a function.
<img width="395" alt="autocomplete-clang - atom 2015-07-08 11-15-53" src="https://cloud.githubusercontent.com/assets/5463365/8561651/a56a9fae-2563-11e5-8731-5d029a90e1d9.png">
Completions while defining an enum are actually noisy but I can type trailing enumerators.
And sometimes I want to type with completion after `:`.
So a solution of the issue is depends on contexts and coding styles.

I guess that adding a configurable setting to disable completions is better choice for this issue.
(The default values for the setting are like `[';',')','}']`)
What do you think about it?

**Comment by ssfrr** [comment]
I'm not sure if disabling completions based on the previous character is the right way to resolve this. I think the main problem is that it's providing a completion list when I haven't typed anything:

![image](https://cloud.githubusercontent.com/assets/734386/8580144/e8b8db40-2586-11e5-999d-2e5b26662486.png)


I have my minimum word length in the autocomplete-plus settings set to 1, so I wouldn't expect to see any completions pop up until after I had started typing something.

**Comment by lczech** [comment]
That last comment about the minimum word length applies also to #77
