### ISSUE TITLE
Suppress completion after a space

### ISSUE THREAD

**Issue by zonyitoo** [yasuyuky/autocomplete-clang#77]
![image](https://cloud.githubusercontent.com/assets/1067951/9768101/28295b52-5754-11e5-899a-5661d53ed587.png)

System: OS X 10.10.5
Atom: 1.0.11

When I type a space, the plugin will try to complete it, which will show some private definitions in the standard libraries.

**Comment by entropy-minus** [comment]
I have the same issue. I also don't actually get the auto-complete options declared in the same file. Debug how can I debug this?

**Comment by lczech** [comment]
Same here. It's particularly annoying if you try to horizontally align stuff and cannot see the lines below the current one...

Suggestion: As one rarely needs any of those double-underscore definitions, it might be best to have a package setting to fully disable them. So, not only fix the issue @zonyitoo mentioned about the list appearing when typing space, but also offer to not show them at all.

**Comment by Pbdas** [comment]
same issue here, I agree with @lczech

**Comment by lczech** [comment]
I just played around with the function `filterForPrefix` in https://github.com/yasuyuky/autocomplete-clang/blob/master/lib/clang-provider.coffee#L49 and tried stuff like

    if (suggestion.snippet or suggestion.text).startsWith("__")
      continue

which kind of worked, but more and more suggestions were produced. First, those with just a single underscore, but after checking for this, too, the suggestions that came up were free functions in the global namespace...

Finally I realized that the problem is something else: The package seems to ignore the `autocomplete-plus` option `Minimum Word Length`!
